name: Promote to prod (manual mirror)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch att promota"
        required: true
        default: "main"
        type: string
      include_tags:
        description: "Skicka taggar också?"
        required: true
        default: "no"
        type: choice
        options: [ "no", "yes" ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repo (utan bot-credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # 🔴 viktigt – annars lagras GITHUB_TOKEN

      - name: Sätt git-identitet
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 🔒 Tvinga alla https://github.com/* att använda din PAT
      - name: Använd PAT för GitHub
        env:
          PROD_PUSH_TOKEN: ${{ secrets.PROD_PUSH_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${PROD_PUSH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Lägg till prod-remote + testa auth
        env:
          PROD_OWNER: ${{ secrets.PROD_OWNER }}   # ex: Herry-t
          PROD_REPO:  ${{ secrets.PROD_REPO }}    # ex: VardagsLadan
        run: |
          set -eu
          git remote add prod "https://github.com/${PROD_OWNER}/${PROD_REPO}.git"
          git remote -v
          git ls-remote prod >/dev/null   # failar direkt om PAT saknar access

      - name: Pusha vald branch till prod
        env:
          BRANCH: ${{ inputs.branch }}
        run: |
          git push prod "${BRANCH}:${BRANCH}"

      - name: Pusha taggar (valfritt)
        if: ${{ inputs.include_tags == 'yes' }}
        run: |
          git push prod --tags
