name: Promote to prod (manual mirror)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch to promote?"
        required: true
        default: "main"
        type: string
      include_tags:
        description: "Push tags too?"
        required: true
        default: "no"
        type: choice
        options: [ "no", "yes" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Viktigt: använd x-access-token + secrets
      - name: Add prod remote (use PAT)
        env:
          PROD_PUSH_TOKEN: ${{ secrets.PROD_PUSH_TOKEN }}
          PROD_OWNER: ${{ secrets.PROD_OWNER }}
          PROD_REPO: ${{ secrets.PROD_REPO }}
        run: |
          set -eu
          REMOTE_URL="https://x-access-token:${PROD_PUSH_TOKEN}@github.com/${PROD_OWNER}/${PROD_REPO}.git"
          git remote add prod "$REMOTE_URL"
          # Testa auth innan push (failar direkt om fel)
          git ls-remote prod >/dev/null

      - name: Push selected branch to prod
        env:
          BRANCH: ${{ inputs.branch }}
        run: |
          git push prod "${BRANCH}:${BRANCH}"

      - name: Push tags (optional)
        if: ${{ inputs.include_tags == 'yes' }}
        run: |
          git push --tags prod
