name: Promote to prod (manual mirror)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch to promote?"
        required: true
        default: "main"
        type: string
      include_tags:
        description: "Push tags too?"
        required: true
        default: "no"
        type: choice
        options: [ "no", "yes" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add prod remote (use PAT)
        run: |
          PROD_URL="https://x-access-token:${{ secrets.PROD_PUSH_TOKEN }}@github.com/${{ secrets.PROD_OWNER }}/${{ secrets.PROD_REPO }}.git"
          git remote add prod "$PROD_URL"
          git remote -v

      - name: Push selected branch to prod
        run: |
          git push prod ${{ inputs.branch }}:${{ inputs.branch }}

      - name: Push tags (optional)
        if: ${{ inputs.include_tags == 'yes' }}
        run: |
          git push --tags prod
